import type {Metadata} from "next";
import "./globals.css";
import {PropsWithChildren} from "react";
import {Providers} from "@/app/providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
      <Providers>
          {children}
      </Providers>
      </body>
    </html>
  );
}
