"""do comment and favorite_music fields optional

Revision ID: ed02c0303ea7
Revises: d1fec140b9a2
Create Date: 2026-02-23 00:38:30.309909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed02c0303ea7'
down_revision: Union[str, Sequence[str], None] = 'd1fec140b9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invitations', 'comment',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('invitations', 'favorite_music',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invitations', 'favorite_music',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('invitations', 'comment',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    # ### end Alembic commands ###
